/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline(
        'https://prod.spline.design/5LlcNaT3stRY2qLI/scene.splinecode'
    );
    return (
        <>
            <color
                attach="background"
                args={['#ced0d7']}
            />
            <group
                {...props}
                dispose={null}
            >
                <mesh
                    name="Rectangle 2"
                    geometry={nodes['Rectangle 2'].geometry}
                    material={materials['Rectangle 2 Material']}
                    castShadow
                    receiveShadow
                    position={[0, -225.05, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={1}
                />
                <mesh
                    name="Rectangle"
                    geometry={nodes.Rectangle.geometry}
                    material={materials['Rectangle Material']}
                    castShadow
                    receiveShadow
                    position={[0, -189.48, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={1}
                />
                <group
                    name="Group 3"
                    position={[157, -45.39, -151.51]}
                >
                    <mesh
                        name="Text"
                        geometry={nodes.Text.geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-43.22, 103.61, -44.92]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={1}
                    />
                    <mesh
                        name="Cube"
                        geometry={nodes.Cube.geometry}
                        material={materials.Key}
                        castShadow
                        receiveShadow
                        position={[0, 45.39, 0]}
                    />
                </group>
                <group
                    name="Group 2"
                    position={[157, -45.39, 154.57]}
                >
                    <mesh
                        name="Text1"
                        geometry={nodes.Text1.geometry}
                        material={materials['Text1 Material']}
                        castShadow
                        receiveShadow
                        position={[-43.22, 103.61, -44.92]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={1}
                    />
                    <mesh
                        name="Cube1"
                        geometry={nodes.Cube1.geometry}
                        material={materials['key orange']}
                        castShadow
                        receiveShadow
                        position={[0, 45.39, 0]}
                    />
                </group>
                <group
                    name="Group 4"
                    position={[-151, -45.39, 154.57]}
                >
                    <mesh
                        name="Text2"
                        geometry={nodes.Text2.geometry}
                        material={materials['Text2 Material']}
                        castShadow
                        receiveShadow
                        position={[-43.22, 103.61, -44.92]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={1}
                    />
                    <mesh
                        name="Cube2"
                        geometry={nodes.Cube2.geometry}
                        material={materials.Key}
                        castShadow
                        receiveShadow
                        position={[0, 45.39, 0]}
                    />
                </group>
                <group
                    name="Group"
                    position={[-151, -45.39, -151.51]}
                >
                    <mesh
                        name="Text3"
                        geometry={nodes.Text3.geometry}
                        material={materials['Text3 Material']}
                        castShadow
                        receiveShadow
                        position={[-43.22, 103.61, -44.92]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={1}
                    />
                    <mesh
                        name="Cube3"
                        geometry={nodes.Cube3.geometry}
                        material={materials.Key}
                        castShadow
                        receiveShadow
                        position={[0, 45.39, 0]}
                    />
                </group>
                <directionalLight
                    name="Directional Light"
                    castShadow
                    intensity={0.57}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-367.3075}
                    shadow-camera-right={367.3075}
                    shadow-camera-top={367.3075}
                    shadow-camera-bottom={-367.3075}
                    position={[-591, 709, 427]}
                />
                <OrthographicCamera
                    name="1"
                    makeDefault={true}
                    zoom={0.66}
                    far={100000}
                    near={-100000}
                    position={[179.88, 693.54, 727.22]}
                    rotation={[-0.81, 0.1, 0.1]}
                />
                <hemisphereLight
                    name="Default Ambient Light"
                    intensity={0.75}
                    color="#eaeaea"
                />
            </group>
        </>
    );
}
